config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chefs do
    resources :bookings, only: [:create, :show]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]

  get "/dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :chef
  belongs_to :user
  validates :chef, presence: true
  validates :user, presence: true
end

app/models/chef.rb
class Chef < ApplicationRecord
  geocoded_by :address
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :name, presence: true
  validates :title, presence: true
  validates :price, presence: true
  #validates :address, presence: true
  validates :photo, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :chefs
  has_many :chef_bookings, through: :chefs, source: :bookings #chefs ia a table

  def is_chef?
    self.chefs.length > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def create
    @chef = Chef.find(params[:chef_id])
    @chef.user_id = current_user.id
    @booking = Booking.new(chef: @chef, user: current_user)
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    end
  end


  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.confirmation = true
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params[:booking].permit(:date, :chef, :user, :confirmation)
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]

  def index
    @chefs = policy_scope(Chef).order(created_at: :desc)
  end

  def show
    authorize @chef
    @markers = [{
      lat: @chef.latitude,
      lng: @chef.longitude
    }]
  end

  def new
    @chef = Chef.new
    authorize @chef
  end

  def edit
    authorize @chef
  end

  def create
    @chef = Chef.new(chef_params)
    @chef.user_id = current_user.id
    @chef.save
    authorize @chef
    redirect_to chef_path(@chef)
  end

  def destroy
    @chef.destroy
    redirect_to chefs_path
  end

  private

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def chef_params
    params.require(:chef).permit(:name, :title, :rating, :description, :price, :categories, :address, :photo, :latitude, :longitude, :chef)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pundit
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @user = current_user
  end

  def inbox
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="title-inbox">Messages</h1>
  <h1> <%= link_to "Go Back", chefs_path , class:"profile. btn"  %> </h1>

  <hr>
  <h3>Received requests</h3>
  <% if current_user.is_chef? %>
  <ul>
    <% Booking.all.each do |booking| %>
    <% if current_user.id == booking.chef.user_id %>
    <li class="message">
      <div class="message-name">
        <h4><%= booking.created_at.strftime("%m/%d/%Y") %>
        </h4>
      </div>
      <div class="message-body">
        <h6><%= link_to User.find(booking.user_id).email, "#"  %> requested you for its event
        </h6>
      </div>
      <div class="status-pending">
        <p> <%= link_to "Confirm", "" %> </p>
      </div>
    </li>
    <% end %>
    <% end %>
    <% end %>
  </ul>
  <hr>
  <h3>Sent requests</h3>
  <ul>
    <% Booking.all.each do |booking| %>
    <% if current_user.id == booking.user_id%>
    <li class="message">
      <div class="message-name">
        <h4><%= booking.created_at.strftime("%m/%d/%Y") %>
        </h4>
      </div>
      <div class="message-body">
        <h6>Chef you've requested: <%= link_to Chef.find(booking.chef.id).name, "#"  %>
        </h6>
      </div>
      <div class="message-status">
        <p> Pending </p>
      </div>
    </li>
    <hr>
    <% end %>
    <% end %>
  </ul>
  <div class="bottom"></div>
</div>

app/views/bookings/show.html.erb
<h1>Please see the details of your booking below:</h1>
<h2>Date: <%= @booking.date %></h2>
<h4>Chef: <%= @booking.chef.name %></h4>
<h4>Location : <%= @booking.user.address %></h4>

app/views/chefs/edit.html.erb
<h1>Edit Chef</h1>

<%= simple_form_for @chef do |f| %>
<%= f.input :name %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.button :submit %>
<%= link_to "Cancel", chefs_path, value: "Publish", class: "btn btn-warning" %>
<% end %>

app/views/chefs/index.html.erb
<div class="container">
  <h1 class="results">Find your chefista</h1>
</div>
<hr>

<div class="container">
  <div class="row">
    <% @chefs.each do |chef| %>
    <div class="card-index">
      <div class="col-xs-12 col-sm-4">
        <div class="card-picture" style="background-image: url('<%= cl_image_path chef.photo %>');">
         <%= link_to "", chef_path(chef), class: "card-link" %>
       </div>
       <div class="chef-details row">
        <%= link_to chef_path(chef) do %>
        <div class="col-xs-8">
          <div class="chef-name">
            <h4> <%= chef.name %> </h4>
            <p> <%= chef.title %> </p>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="price">
            <% if chef.price == 0 %>
              <span><%= "FREE" %></span>
            <% else %>
              <span><%= chef.price %>€</span> <span>pp</span>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/chefs/new.html.erb
<div class="newchefpage">
  <div class="container-newchef">
    <h1>Share Your Chef Skills With The World</h1>

    <%= simple_form_for @chef do |f| %>
    <%= f.input :name %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit %>
    <%= link_to "Cancel", chefs_path, value: "Publish", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/chefs/show.html.erb
<div class="container-chef-show">
  <div class="profile text-center">
    <div class="main">
      <div class="main-content">
        <%= cl_image_tag(@chef.photo, width: 250, height: 250, crop: :fill, class:"img-circle") %>
        <div class="chef-info">
          <h2><%= @chef.name %></h2>
          <p><%= @chef.title %></p>
          <% if current_user && current_user.id == @chef.user_id %>
          <p>This is your listing!</p>
          <%= button_to "Delete", chef_path(@chef), class:"profile. btn", method: :delete %>
          <% else %>
          <%= button_to "Book this chef", chef_bookings_path(@chef), class:"profile. btn" %>
          <% end %>
          <%= link_to "Go Back", chefs_path , class:"profile. btn"  %>
        </div>
      </div>
    </div>
    <div class="stat">
      <div class="stat-content">
        <h3>5/5</h3>
        <p>Rating</p>
      </div>
    </div>
    <div class="stat">
      <div class="stat-content">
        <h3>187</h3>
        <p>Meals Total</p>
      </div>
    </div>
    <div class="stat">
      <div class="stat-content">
        <h3>22</h3>
        <p>Dishes</p>
      </div>
    </div>
    <div class="description">
      <div class="description-content">
        <h3>More about this chef</h3>
        <p class="text-justify">
          <%= @chef.description.nil? ? "No description available" : @chef.description %>
        </p>
      </div>
    </div>
  </div>
</div>

<div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Chefista</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body class="<%= action_name %>">
  <%= render 'shared/flashes' %>
  <%= render 'shared/navbar' %>
  <div class="wrapper">
    <%= yield %>
  <%= render 'shared/footer' %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
  <%= javascript_pack_tag "maps" %> <!-- add this line -->
</body>
</html>

app/views/pages/home.html.erb
<div class="body-background">
  <div class="banner">
    <div class="banner-content">
      <h1 class="website_name">Chefista</h1>
      <h2>Book a classy dinner at home</h2>
      <p>Forget the hassle, enjoy the experience</p>
      <%= link_to "Find me a chef!", chefs_path, class: "button-chef"%>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div> -->

<div class="footer">
    <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <a href="#"><i class="fab fa-github"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-facebook"></i></a>
                </div>
                <div class="col-xs-6 text-right">
                    <p>Powered by <i class="fab fa-twitter" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; © 2017</p>
                </div>
            </div>
        </div>
  </div>

app/views/shared/_index.html.erb
<h1>This is the chef index page</h1>
<hr>
<div class="menu">
  <%= link_to "Add A Chef", new_chef_path, class: "menu_item"%>
</div>
<hr>
<div class="row">
  <% @chefs.each do |chef| %>
  <div class="card">
    <div class="card-description">
      <h4> <%= link_to chef.name, chef_path(chef) %> </h4>
    </div>
  </div>

  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "chefista_white.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <% if user_signed_in? %>
    <% if current_user.is_chef? %>
    <%= link_to "Inbox", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
    <%= link_to "Become A Chef!", new_chef_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Inbox", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>


    <!-- Avatar with dropdown menu -->

    <%= link_to destroy_user_session_path, class: "log-out-link", method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>

    <% end %>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>